### ISSUE TITLE
Why is it giving this error once it reaches usernames page

### ISSUE THREAD

**Issue by paulsblackfriday** [redianmarku/instagram-follower-scraper#13]
Im running into to this and i twas fine just two 3 days ago, its telling me the selenium isnt working:
the folders within: site-packages/  should i delete then run to install them again? 
two folders are in it existing as: selenium-3.141.0.dist-info\  and selenium\. 

C:\Users\Paul\Downloads\Instragram Follows Test>python run.py
[Required] - Whose followers do you want to scrape: ___username censored here
[Required] - How many followers do you want to scrape (60-500 recommended): 500

[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST driver version for 102.0.5005
[WDM] - Driver [C:\Users\Paul\.wdm\drivers\chromedriver\win32\102.0.5005.61\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:57190/devtools/browser/6609293c-b8d9-4ddf-96c0-7033a83a7f84
[Info] - Logging in...
**Traceback (most recent call last):
  File "C:\Users\Paul\Downloads\Instragram Follows Test\run.py", line 103, in <module>
    scrape()
  File "C:\Users\Paul\Downloads\Instragram Follows Test\run.py", line 69, in scrape
    WebDriverWait(bot, TIMEOUT).until(
  File "C:\Users\Paul\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:**

C:\Users\Paul\Downloads\Instragram Follows Test>

C:\Users\Paul\Downloads\Instragram Follows Test>

**Comment by tgrander** [comment]
Replace that xpath value with `"//a[contains(@href, '/following')]"` which will successfully access the link even if the exact xpath changes in the future.

**Comment by MitoNftlab** [comment]
> 

pls bro
which of the xpath value should we replace

**Comment by ju0n3** [comment]
i change `EC.presence_of_element_located((
            By.XPATH, '//*[@id="react-root"]/section/main/div/ul/li[2]/a'))).click()`

into this `EC.presence_of_element_located((
            By.XPATH, "//a[contains(@href, '/following')]"))).click()`

but somehow it return nothing to followers.txt file

**Comment by CreaTorAlexander** [comment]
Yes, I have the same issue, I also updated the path in line 86 where it uses the same path element, but my resulting text file is still empty.

**Comment by CreaTorAlexander** [comment]
I solved it by replacing line 86 with
`"//a[contains(@href, '/')]")`
