### ISSUE TITLE
Issue after logging in

### ISSUE THREAD

**Issue by Okrbx** [redianmarku/instagram-follower-scraper#5]
Hi after i login it takes me to the page of the person i want to scrape followers usernames from then it shows this Traceback (most recent call last):
  File "C:\Users\not2d\Desktop\instagram-follower-scraper-master\run.py", line 104, in <module>
    scrape()
  File "C:\Users\not2d\Desktop\instagram-follower-scraper-master\run.py", line 64, in scrape
    WebDriverWait(bot, TIMEOUT).until(
  File "C:\Users\not2d\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Any help please?

**Comment by runn454** [comment]
same for me... 

  File "C:\Users\glenr\Desktop\instagram-follower-scraper-master\run.py", line 103, in <module>
    scrape()
  File "C:\Users\glenr\Desktop\instagram-follower-scraper-master\run.py", line 69, in scrape
    WebDriverWait(bot, TIMEOUT).until(
  File "C:\Users\glenr\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by mofaizanfdns** [comment]
Same issue for Me. Hey @redianmarku please give any solution

**Comment by Miap93** [comment]
same problem here. help?
