### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by mediopolis** [redianmarku/instagram-follower-scraper#8]
I now get an error when trying to run the script. 

[Info] - Logging in...
Traceback (most recent call last):
  File "C:\Users\mediopolis\Desktop\scraper\run.py", line 103, in <module>
    scrape()
  File "C:\Users\mediopolis\Desktop\scraper\run.py", line 69, in scrape
    WebDriverWait(bot, TIMEOUT).until(
  File "C:\Users\mediopolis\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message

**Comment by mediopolis** [comment]
fixed. just needed to update the XPATH

**Comment by Dhelvis** [comment]
> fixed. just needed to update the XPATH

Could you share new path?

**Comment by ardanazz** [comment]
new xPath (if your IG is in another language, you should replace 'followers' with 'followersInYourLanguage'): //a[contains(.,'followers')]

**Comment by ardanazz** [comment]
> //a[contains(.,'followers')]

Also need to change followers variable to:
        followers = bot.find_elements_by_xpath(
            '//*/div[@role="button"]/a')

**Comment by newdispatcher** [comment]
it worked but it didn't scrap followers & no entry in followers.txt.
please help!!!

**Comment by newdispatcher** [comment]
> fixed. just needed to update the XPATH

how you updated the Xpath?

**Comment by ardanazz** [comment]
> > fixed. just needed to update the XPATH
> 
> how you updated the Xpath?

see last 2 comments, just need to edit run.py with a text editor like notepad, sublime text, etc.

**Comment by newdispatcher** [comment]
After your edits it worked!!! Thanks

**Comment by mofaizanfdns** [comment]
> > //a[contains(.,'followers')]
> 
> Also need to change followers variable to:
> 
> ```
>  followers = bot.find_elements_by_xpath( '//*/div[@role="button"]/a')
> ```

Please ReWrite the entire link another time. I cant understand your previous comments

**Comment by frodas20** [comment]
> > > fixed. just needed to update the XPATH
> > 
> > 
> > how you updated the Xpath?
> 
> see last 2 comments, just need to edit run.py with a text editor like notepad, sublime text, etc.

I edited it and said it scraped but when i look at my followers.txt there's nothing? can someone help me out?

**Comment by Arctic25** [comment]
Hi,
I changed the xPath as suggested, but it NOT working, the "follower.txt" file is empty.
Here the code changed, could you please chek if it correct  @mofaizanfdns, @ardanazz:

WebDriverWait(bot, TIMEOUT).until(
        EC.presence_of_element_located((
            By.XPATH, '//a[contains(.,"followers")]'))).click()

Thanks in advance
